### ISSUE TITLE
beast-testing-1.0.tar.gz missing

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/BEaST#11]
testing files used to be at https://www.bic.mni.mcgill.ca/~vfonov/temp/beast-testing-1.0.tar.gz

Now missing :)

**Comment by vfonov** [comment]
Oops, probably it's better to host them on github

**Comment by vfonov** [comment]
https://github.com/BIC-MNI/BEaST/releases/download/release-1.20.00/beast-testing-1.0.tar.gz

**Comment by gdevenyi** [comment]
Great!

**Comment by vfonov** [comment]
I didn't modify build system yet

**Comment by gdevenyi** [comment]
Am aware thanks.
