### ISSUE TITLE
beast_normalize error: No points were chosen by the specified criteria

### ISSUE THREAD

**Issue by andrewlkho** [BIC-MNI/BEaST#12]
[head.mnc.zip](https://github.com/BIC-MNI/BEaST/files/5505234/head.mnc.zip)

I am having trouble running beast_normalize on my dataset.  I am using minc-toolkit-v2 1.9.16 installed with the supplied [singularity container](https://bic-mni.github.io/#containers).  The command I am running is:

    singularity exec ~/singularity/minc-toolkit-1.9.16.simg \
      beast_normalize head.mnc head_mni.mnc tmp/anat2mni.xfm \
      -modeldir /opt/minc/share/icbm152_model_09c

After the "Transforming slices..." step, it exits with the message:

    No points were chosen by the specified criteria
    resample_labels: crashed while running extracttag (termination status=256)
    nu_estimate_np_and_em: crashed while running resample_labels (termination status=256)
    nu_correct: crashed while running nu_estimate_np_and_em (termination status=256)

I have attached an example image file that I am using; the scan is derived from a scan in the public domain: TCIA-GBM collection (subject TCGA-12-3650).

How can I debug?  Given that it happens with all scans in my database, this must either be a problem with my install or the dataset I am using but I am at a loss as to progress further.  I would be grateful for any advice.

**Comment by gdevenyi** [comment]
Hi, your example file has an incorrect intensity range with a large number of voxels < 0:

![image](https://user-images.githubusercontent.com/3001850/98450609-f3964300-210b-11eb-9c7c-41da151505f1.png)

You can renormalize the intensity range with something like:
```
mincnorm -cutoff 0 head.mnc head_renorm.mnc
```

Having said that, the file you provided is not a T1-weighted image, so unless you're providing custom beast priors which have a similar contrast to these scans, I don't expect BeAST to work on this dataset.

**Comment by andrewlkho** [comment]
That's odd.  The original NIFTI image (attached) is a T1 image which correctly displays in ITK-SNAP:

<img width="1080" alt="Screenshot 2020-11-08 at 01 35 33" src="https://user-images.githubusercontent.com/8575/98454974-bdd07900-2162-11eb-8a7f-f3b25aeda24b.png">

The intensity values in the NIFTI file are normalised to zero-mean unit-variance within the brain itself.  This was then converted to MNC with:

    nii2mnc head.nii head.mnc

Presumably it would be best to put it in a "correct" intensity range for MNC prior to conversion.  What does MNC expect the intensity range to be?

[head.nii.zip](https://github.com/BIC-MNI/BEaST/files/5505748/head.nii.zip)

**Comment by gdevenyi** [comment]
That's not a T1-weighted image. That's a low-resolution PD image.

This is a T1:
![image](https://user-images.githubusercontent.com/3001850/98455785-40494080-2143-11eb-8ff5-e184db2ff424.png)

> The intensity values in the NIFTI file are normalised to zero-mean unit-variance within the brain itself

I can think of no image-processing pipeline that will handle that well. That sounds like something you might do at the end if you wanted to do statistical learning/ML. Stick with positive values for image processing.

> What does MNC expect the intensity range to be?

MINC itself can handle any range of values including complex numbers, but most of the image processing tools assume positive values.

**Comment by andrewlkho** [comment]
Thanks for the feedback Gabriel.  You are quite right, that is a proton density image that has crept into the dataset (in fact, the BraTS dataset) and labelled as T1.  Thanks also for the information about intensity values; I hadn't realised that the actual range mattered for image processing as (as you rightly infer) it was part of my ML pre-processing pipeline.

As I suspected, this is a "my dataset" problem not a BeAST problem so consider this issue closed.

**Comment by gdevenyi** [comment]
Good luck and feel free to come back anytime for new questions!
