### ISSUE TITLE
minc/minc-toolkit-v2/BEaST/nlmsegFuzzy.c(271): error: invalid parallel pragma

### ISSUE THREAD

**Issue by poquirion** [BIC-MNI/BEaST#2]
I got a pragma error on beast while compiling beast with the minc toolkit v2 

On fedora 23 

icpc --version
icpc (ICC) 15.0.3 20150407
Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.

```
minc/minc-toolkit-v2/BEaST/nlmsegFuzzy.c(271): error: invalid parallel pragma
        #pragma parallel for reduction(+:count)
```

... And just commented the line.

**Comment by vfonov** [comment]
Did you enable openMP ?

**Comment by poquirion** [comment]
`-DMT_USE_OPENMP:BOOL=ON` : It was enable indeed

I also had to add these flag to get the intel compilation working.

-DCMAKE_CXX_COMPILER=icpc 
-DCMAKE_C_COMPILER=icc  
-DCMAKE_CXX_FLAGS:STRING=-static-intel
-DCMAKE_C_FLAGS:STRING=-static-intel

**Comment by gdevenyi** [comment]
Fixed
