### ISSUE TITLE
beast_prepareADNIlib error

### ISSUE THREAD

**Issue by xhs400** [BIC-MNI/BEaST#5]
The minc tool kit that I install with command ('dpkg -i .deb') is located in /opt/minc/1.9.16 (1.9.16 is the version). However, in the beast_prepareADNIlib line 61, it tries to locate 'minc-toolkit-config.sh' under /opt/minc/, but couldn't find it. I can adapt it to my code, but I feel it is desirable to have a more general way to do that.

**Comment by vfonov** [comment]
The easiest would be to source appropriate minc-toolkit-config manually and remove lines 61-66 in https://github.com/BIC-MNI/BEaST/blob/master/scripts/beast_prepareADNIlib#L61
